### ISSUE TITLE
How to contribute to the Tutorial PDF?

### ISSUE THREAD

**Issue by terbos90803** [FRCTeam3255/FRC-Java-Tutorial#2]
Is the source PPT available for the tutorial?  Can anyone else contribute to updates?

**Comment by TaylerUva** [comment]
As of right now, I do not have the source available. I actually had not thought of taking contributions but that is a good idea. I will try to think of the best way to accomplish this.

**Comment by TaylerUva** [comment]
I am currently in the process of converting the tutorial from a PPT to the [MKDocs](https://www.mkdocs.org) format. This will allow for outside contributions as now all pages are written in Markdown.

The tutorial documentation will now be available [here](https://frcteam3255.github.io/FRC-Java-Tutorial/), with each page having the option to edit.

This also allows people to contribute entirley new pages as well.

More info:
[Contributing](https://frcteam3255.github.io/FRC-Java-Tutorial/contributing.html)
